DEFINES+=PROJECT_CONF_H=\"../02-ipv6/project-conf.h\"

all: mqtt-demo

APPS += mqtt

# Linker size optimization
SMALL = 1

CONTIKI_WITH_IPV6 = 1

CONTIKI = ../../../..

include $(CONTIKI)/Makefile.include
